### PR TITLE
New Sample for Js Viewer

### PR DESCRIPTION
**Pull request by sAbakumoff**
The new sample shows how to use Js Viewer with the most recent React version. The sample is using hooks and context API

### CODE REVIEW

**Comment by Alex493049469** [comment]
After restoring and rebuild, node_modules folder is shown in the VS project.
There are a lot of files and folders.
Please exclude it from the project.

Why two more .gitignore files?
At the root of the repository there is already a .gitignore, modify it if need.

This is a new sample on core 3.1, rename it please to JSViewer_React_Hooks (Core).
Thanks.

**Comment by sAbakumoff** [comment]
@Alex493049469 node_modules folder is by design, it's the same as for other JS Viewer samples
It's how react app works
and if anything, it's not in the project!

**Comment by sAbakumoff** [comment]
I also don't agree with renaming, (Core) addition is not necessary

**Comment by sAbakumoff** [comment]
additional .gitignore file is specific for the clientapp, that's by design

**Pull request merged**
